Login/Login/Controllers/AutenticacaoController.cs
using Login.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Login.Controllers
{
    public class AutenticacaoController : Controller
    {

        /// <summary>
        /// login
        /// </summary>
        /// <param name="nome"></param>
        /// <param name="login"></param>
        /// <param name="senha"></param>
        /// <returns></returns>
        public JsonResult autenticaUsuario(String nome, String login, String senha)
        {

            string Nome = Request[nome];
            string Login = Request[login];
            string Senha = Request[senha];

            Usuarios Usuario = new Usuarios(Nome, Login, Senha);


            ////este controler deve retornar um status http 404 ou similares caso usuario nao seja encontrado

            return Json("", JsonRequestBehavior.AllowGet);


        }


        /// <summary>
        /// logout
        /// </summary>
        /// <param name="login"></param>
        /// <param name="senha"></param>
        /// <returns></returns>
        public Boolean deslogarUsuario(String login, String senha)
        {

            string Login = Request[login];
            string Senha = Request[senha];

            Usuarios Usuario = new Usuarios(Login, Senha);

            return true;


        }

        public ActionResult Login()
        {
            return View();
        }
    }
}

Login/Login/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Login.Controllers
{
    public class HomeController : Controller
    {
  

        // GET: Home
        public ActionResult Menu()
        {
            return View();
        }



    }
}

Login/Login/Controllers/SefazController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Login.Controllers
{
    public class SefazController : Controller
    {

        /// <summary>
        /// Realizar um DTO - OBJECT e retornar o Json
        /// </summary>
        /// <returns></returns>
        public JsonResult obterListaPedidosSefaz()
        {

            return Json("seu json aqui", JsonRequestBehavior.AllowGet);


        }

        [HttpPost]
        public Boolean statusAgendados(Boolean seletor)
        {
            Boolean estadoAgendador = Boolean.Parse(Request[""+seletor]);

            return true;

        }


        [HttpPost]
        public Boolean alterarChave(String chave)
        {
            String Chave = Request[chave];

            return true;


        }

        public ActionResult ListaSefaz()
        {
            return View();
        }


        public ActionResult ConfigSefaz()
        {
            return View();
        }

        
    }
}

Login/Login/Controllers/ToolsSefazController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Login.Controllers
{
    public class ToolsSefazController : Controller
    {
        // GET: ToolsSefaz
        public ActionResult ConfigSefaz()
        {
            return View();
        }
    }
}

Login/Login/Controllers/UsuariosController.cs
using Login.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Web.Mvc;
using System.Windows.Forms;

namespace Login.Controllers
{
    public class UsuariosController : Controller
    {



        [HttpPost]
        public Boolean excluirUsuario(int id)
        {

            int Id =  Int32.Parse(Request[""+id]);

            Usuarios Usuario = new Usuarios(Id);

            return true;


        }

        [HttpPost]
        public Boolean cadastrarUsuario(String nome, String login, String senha)
        {

            //   caso haja falha, retornar um http status

            return true;


        }


        /// <summary>
        /// sobre carga para alteracao dos dados menos a senha
        /// </summary>
        /// <param name="id"></param>
        /// <param name="nome"></param>
        /// <param name="login"></param>
        /// <returns></returns>
        [HttpPost]

        public Boolean alterarUsuario(int id, String nome, String login)
        {

            return true;


        }


        /// <summary>
        /// sobre carga para alteracao completa
        /// </summary>
        /// <param name="id"></param>
        /// <param name="nome"></param>
        /// <param name="login"></param>
        /// <param name="senha"></param>
        /// <returns></returns>
        [HttpPost]
        public Boolean alterarUsuario(int id, String nome, String login, String senha)
        {

            return true ;


        }

        /// <summary>
        /// Realizar um DTO - OBJECT e retornar o Json
        /// </summary>
        /// <returns></returns>
        public JsonResult obterListaUsuarios()
        {

           //DTO - object
          //    --> importante :  fazer um parse para object  



            return Json("seu json aqui", JsonRequestBehavior.AllowGet);


        }





        //renderizador

        public ActionResult TabelaUsuarios()
        {
            return View();
        }

    }
}

Login/Login/Views/Home/Menu.cshtml
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Promoserv Menu</title>

    <link href="~/estilos/Menu.css" rel="stylesheet" />

</head>

<body>


    <header>

        <a href="@Url.Action("Login", "Autenticacao")" id="Sair" class="SaidaBarra">
            <ion-icon name="exit-outline"></ion-icon>&nbsp&nbspDeslogar
        </a>
        <h3>Sistema Promoserv</h3>
    </header>


    <input type="checkbox" name="" id="chk">
    <label for="chk" class="menu-icon">&#9776;</label>

    <div class="bg"></div>

    <nav class="menu" id="principal">

        <ul>

            <li>
                <a href="" class="voltar" id="mainret">
                    <ion-icon name="arrow-back-outline"></ion-icon>
                </a>
            </li>
            <li>
                <a href="@Url.Action("TabelaUsuarios", "Usuarios")" target="MainFrame" id="HUser">
                    <ion-icon name="person-outline"></ion-icon>&nbsp&nbspMenu Usuarios
                </a>
            </li>
            <li>

                <a href="@Url.Action("ListaSefaz", "Sefaz")" id="pedidosSefaz" target="MainFrame">
                    <ion-icon name="documents-outline"></ion-icon>&nbsp&nbspSefaz
                </a>
            </li>
            <li>

                <a href="@Url.Action("ConfigSefaz", "ToolsSefaz")" id="ConfigSefaz" target="MainFrame">
                    <ion-icon name="hammer-outline"></ion-icon>&nbsp&nbspConfig Sefaz
                </a>
            </li>
            <li>

                <a href="@Url.Action("Login", "Autenticacao")" id="Sair">
                    <ion-icon name="exit-outline"></ion-icon>&nbsp&nbspSair
                </a>
            </li>


        </ul>


    </nav>


    <iframe frameborder="0" name="MainFrame" id="MainFrame">
    </iframe>


</body>

</html>

<script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>

<script src="~/Assets/Uteis/jquery.js"></script>

<script src="~/Assets/menu/Main.js"></script>
<script src="~/Assets/menu/ControladorEventosTela.js"></script>

<script>



    $('#ConfigSefaz').click(function () {

        $('#principal').css("transform", "translate(-300px)");
        $("div").removeClass("bg");
    });



</script>